### ISSUE TITLE
Increase the amount of markers being able to show

### ISSUE THREAD

**Issue by natrius** [printmaps/printmaps#11]
I exported needed data with 
```

[out:csv(::id,name,::lon,::lat; true; "|")] // write csv 
[bbox:{{bbox}}]; // use bbox to get data
nwr[shop=supermarket]; // node, way,relation
out center; // get center of every datapoint
```
and changed it a little bit up with notepad++ so it matches sample1, but it seems like printmaps decides random on what to display. Using the following data

```
id|name|wkt
18|Open Air Museum|POINT(13.05 47.83)
19|Zoo|POINT(13.04 47.82)
1|Billa Plus|POINT(13.0673673 47.7776952)
2|Edeka|POINT(13.9527000 47.8142000)
```

The first 2 will get shown, the last one do not. At first i thought its the digit-number, but now i have an file with 137 supermarkets but on the map there are just 18 shown. Is there a rule on what is getting shown? Or how much markers are getting shown?

Or do i have to change something?

**Comment by printmaps** [comment]
There is no limit concerning the number of markers. Please add your csv file (137 supermarkets) for further investigation. Also helpful: your rendering instruction for the POIs. Perhaps an overlapping problem with displacement / suppresion?

**Comment by natrius** [comment]
Hm, i thought about overlapping, but in my opinion i would see a giant weirdly-shaped marker if they simply overlap. Map-ID `4047bafc-7d2d-4491-82d0-54cc8439e58a` 

At first i could not see anything and thought it was digit-lengths but after some more digging around i simply switched lat and long *coughing*

.csv added, maybe there is an error? I thought about the ID but i could not be bothered to manually rewrite them (or with excel drag down) yet. 

[supermarkets.csv](https://github.com/printmaps/printmaps/files/7754612/supermarkets.csv)

```
# supermarkets pois (csv-wkt data)
- Style: |
         <MarkersSymbolizer file='Printmaps_Ball_Left_Blue.svg' transform='scale(1.0, 1.0)' allow-overlap='true' placement='point' />
         <TextSymbolizer fontset-name='fontset-2' size='20' fill='black' dy='14' allow-overlap='true' placement='point'>[name]</TextSymbolizer>
  SRS: '+init=epsg:4326'
  Type: csv
  File: supermarkets_6digits.csv
  Layer:
```

Thats from the .yaml for the markers. It was 'scale(1.3, 1.3)' before but i switched it (was not able to upload yet, have to wait till home cause of proxy :D )
